FROM python:3.11-slim-bullseye

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    libjpeg-dev zlib1g-dev \
 && apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /app

RUN pip install poetry poetry-plugin-export

COPY src/pyproject.toml src/poetry.lock* ./

RUN poetry lock && poetry install --no-root

COPY src/ .

# Standard-Befehl, um den Container am Leben zu halten.
CMD echo "Entwicklungs-Container läuft. Führe 'docker-compose exec led-matrix-dev bash' aus, um eine Shell zu bekommen." && tail -f /dev/null